### ISSUE TITLE
Authentication with the Admin Hub using Laravel Sanctum

### ISSUE THREAD

**Issue by jbaron-mx** [getcandy/hub#1]
I'm struggling to get the authentication working with the Admin Hub.
I have the API working with Sanctum, and I've tested it by calling some endpoints. However, I'm not sure how to configure the `PROXY_LOGIN_ENDPOINT` in the Hub side to get it working with the API and Sanctum.

I don't mean to rush you guys, but hopefully, you can write up the guide here https://guides.getcandy.io/hub/authentication.html#laravel-sanctum

**Comment by dalholm** [comment]
@jbaron-mx i had the same wish and after i spent some time following the code its very easy to setup. 
In my project i used sanctum token authentication. [laravel sanctum docs](https://laravel.com/docs/7.x/sanctum#api-token-authentication)

1. make sure that your laravel project with getcandy has laravel sanctum installed for token authentication. Common mistake on sanctum token authentication is that you forget to remove `EnsureFrontendRequestsAreStateful::class` from `Kernel`. So make sure that this is removed. 

2. Make sure that you have your routes protected under sanctum [see docs](https://guides.getcandy.io/api/protecting-routes.html#sanctum)

3. Add this to your API routes file
```php
// routes/api.php

Route::post('/sanctum/token', function(Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required'
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return [
        'token_type' => 'Bearer',
        'access_token' => $user->createToken('test')->plainTextToken
    ];
}); 
```


This response will give the hub what it wants and the hub till add a authentication header with Bearer [TOKEN]

4. Configure your hub .env file.
In this example we have a store named store.test and our core software is on a subdomain.

```env
API_BASE=http://core.store.test/api/v1
API_HOST=http://core.store.test
PROXY_LOGIN_ENDPOINT=http://core.store.test/api/sanctum/token
PROXY_USER_ENDPOINT=http://core.store.test/api/v1/users/current
PRODUCT_PREVIEW_URL=http://store.test/products/preview/:id
```

**Comment by jbaron-mx** [comment]
You're the man @dalholm! It worked perfectly. At least, I can play with the Hub's features now, let's see if the candy team releases a guide similar to this along with recommendations or best practices. Thanks again!

**Comment by alecritson** [comment]
@dalholm @jbaron-mx We have now released guides on how you can do this in the hub https://guides.getcandy.io/getting-started/hub/authentication#laravel-sanctum

**Comment by daniel-farina** [comment]
@alecritson 

Thank you for the guide. On a fresh installation I'm facing the following error after following your guide:

![image](https://user-images.githubusercontent.com/13665117/84553099-09c8e000-ace1-11ea-9c80-73ec3946b588.png)

I also was unable to find anywhere a place to set the strategy, what file is this supposed to go to? 

```
auth: {
  strategies: {
    proxy: {
      _scheme: '@getcandy/hub-core/src/modules/sanctum-scheme.js',
      // ...
    }
  }
}
```

The login also responds with an empty payload, is there anyway we could look at a sample Laravel repo that has everything configured on the Laravel side? 

Thanks!

**Comment by dalholm** [comment]
> @alecritson
> 
> Thank you for the guide. On a fresh installation I'm facing the following error after following your guide:
> 
> ![image](https://user-images.githubusercontent.com/13665117/84553099-09c8e000-ace1-11ea-9c80-73ec3946b588.png)
> 
> I also was unable to find anywhere a place to set the strategy, what file is this supposed to go to?
> 
> ```
> auth: {
>   strategies: {
>     proxy: {
>       _scheme: '@getcandy/hub-core/src/modules/sanctum-scheme.js',
>       // ...
>     }
>   }
> }
> ```
> 
> The login also responds with an empty payload, is there anyway we could look at a sample Laravel repo that has everything configured on the Laravel side?
> 
> Thanks!

@daniel-farina that would be in the nuxt.config.js file, but is your installation fresh since the new documentation that strategi is their by default.

**Comment by daniel-farina** [comment]
@dalholm 
Ok I can confirm nuxt.config.js is fine, I did a fresh installation and no luck still. 

The error seems to be with the candy install.

```
{message: "Call to a member function encodedId() on null", exception: "Error",…}
exception: "Error"
file: "/var/www/candy/foodui/vendor/getcandy/candy-api/src/Http/Controllers/Users/UserController.php"
line: 77
message: "Call to a member function encodedId() on null"
trace: [,…]
```

I'll open an issue in the  candy repo and investigate. Thanks!

**Comment by darkshifty** [comment]
Yeah, this had me bumping my head too. However the issue is relatively clear as the the user data isn't available. This can have multiple reasons, one of them is that the request never passed Sanctum.

The right way to add sanctum is as following, add the following line to the `app/Http/Kernel.php`
`use Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful;`

and the following line to the $middleware array and not the middleware group as explained in the docs.
 `EnsureFrontendRequestsAreStateful::class,`

**Comment by alecritson** [comment]
People seem to get stuck on this quite often, so we're going to be overhauling the docs as they're obviously not doing their job at the moment :)

**Comment by alecritson** [comment]
Closed for lack of activity, we're updating the guides to provide a hopefully more streamlined install process.
