### ISSUE TITLE
Description editor on Products page ignores whitespaces.

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#10]
When trying to add a description to a product, the description editor ignores whitespaces.

[Example](https://i.imgur.com/qIKMljS.mp4).

**Comment by alecritson** [comment]
Looks like something is happening in the scrumpy editor when updating it wasn't preserving whitespace. Pushed an update to the core module, also added a debounce on typing so it doesn't spam the save.

```
npm update @getcandy/hub-core
```

Should pull the latest down.

**Comment by Repox** [comment]
The whitespace issue has been resolved.

> also added a debounce on typing so it doesn't spam the save.

With every keystroke, a XHR request is generated to save the current draft, though, spamming the page with "product saved" notifications.

**Comment by alecritson** [comment]
Yeah it's not great, I was thinking maybe to do something when the input is blurred instead? open to suggestions.

**Comment by Repox** [comment]
Blurred would work; it's like a user gesture that would result in an automatic update of the draft.

**Comment by alecritson** [comment]
I've pushed a release to `@getcandy/hub-core` which now uses the blurred event to save, hopefully this will stop the spamming.

**Comment by Repox** [comment]
Just pulled the latest; drafting doesn't work now, so I can't effectively test it.

The error I'm getting when trying to change the short description, and the autosave executes, is the following:

```
Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer_group_id' in 'field list' (SQL: insert into `products` (`attribute_data`, `option_data`, `deleted_at`, `product_family_id`, `layout_id`, `group_pricing`, `drafted_at`, `draft_parent_id`, `customer_group_id`, `product_id`, `visible`, `purchasable`, `channel_id`, `published_at`, `updated_at`, `created_at`) values ({"name": {"webstore": {"en": "tempora voluptatem sunt aut"}}, "page_title": {"webstore": {"en": null}}, "description": {"webstore": {"en": null}}, "meta_keywords": {"webstore": {"en": null}}, "meta_description": {"webstore": {"en": null}}, "short_description": {"webstore": {"en": "He"}}}, [], ?, 1, ?, 0, 2020-06-19 07:03:35, 60022, 1, 60022, 1, 1, 1, 2020-06-17 20:18:04, 2020-06-19 07:03:35, 2020-06-19 07:03:35)) in file /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
```

**Comment by alecritson** [comment]
Yeah doesn't look like a hub issue. Will have a look also, not sure how/why the search branch would effect this though.

**Comment by alecritson** [comment]
Closing as I think this is solved in the latest release. If not feel free to re open :)
