### ISSUE TITLE
Category index page fails as the search request asks for nonexisting relationships and fails

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#19]
When visiting the category index in the hub, the search query parameters ask for the following inclusions:

- `channels`
- `customer_groups`
- `family`
- `variants`
- `assets.transforms`

The `family` and `variants` does not exist on the `Category` model in the API and therefore fails.

**Comment by alecritson** [comment]
This should be solved in `0.9.15` of `@getcandy/hub-categories`

**Comment by Repox** [comment]
Confirmed solved.
