### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by sameh0** [getcandy/hub#3]
Whenever i try to add a product 
undefined is not an object (evaluating '_vm.data[attribute.handle][_vm.fallbackChannel][ _vm.fallbackLanguage ]')

**Comment by alecritson** [comment]
Have you got channels and languages set up in the database on the API?

**Comment by sameh0** [comment]
> Have you got channels and languages set up in the database on the API?

Yes in the Initial setup , and i even created new to be sure using the API . doesn't solve the problem .

**Comment by alecritson** [comment]
Okay sorry about this, I'll try a fresh install and see if I can provide any insight/fix this for you!

**Comment by dalholm** [comment]
> Whenever i try to add a product
> undefined is not an object (evaluating '_vm.data[attribute.handle][_vm.fallbackChannel][ _vm.fallbackLanguage ]')

i had the same problem, but after deleting the database and run the installation cli command once more it all worked.

**Comment by sameh0** [comment]
> > Whenever i try to add a product
> > undefined is not an object (evaluating '_vm.data[attribute.handle][_vm.fallbackChannel][ _vm.fallbackLanguage ]')
> 
> @sameh0 i had the same problem, but after deleting the database and run the installation cli command once more it all worked.

That worked. Thanks

**Comment by dalholm** [comment]
@alecritson maybe this is a bug? look at the database i sent you on discord and see if there are something missing the first run. 

Question, are there any migrations that depends on the env variables except the database variables?

**Comment by alecritson** [comment]
I think I managed to track this one down.

Just out of curiosity, when you reran the installer, did you opt for `webstore` as a channel name?

**Comment by dalholm** [comment]
@alecritson i don't remember the first run, but the second time I just run with defaults.

**Comment by reachnetworkco** [comment]
> I think I managed to track this one down.
> 
> Just out of curiosity, when you reran the installer, did you opt for `webstore` as a channel name?

Yes I did , I am not sure if that was the case with the first run

**Comment by alecritson** [comment]
This was an issue with the hub assuming `webstore` was the channel handle on the page, should be addressed for new installs now if you can upgrade.

https://guides.getcandy.io/hub-guides/0.9/introduction/upgrading#upgrading-from-091-to-092

**Comment by alecritson** [comment]
Going to close this, if updating doesn't solve the issue feel free to reopen
