### ISSUE TITLE
When publishing a draft, Hub doesn't reflect the updated Hash ID for a new table entry

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#4]
When editing a product and adding details or assets a draft of the product is created. When publishing the draft, the Hub doesn't change URL to the new product Hash ID until you navigate to a submenu.

If you try and edit the current page details, the page fails, since it refers to the old Hash ID

**Comment by alecritson** [comment]
This should be addressed in the latest version of the hub and modules, please see upgrade guides

https://guides.getcandy.io/hub-guides/0.9/introduction/upgrading#upgrading-from-091-to-092

If it's still an issue I will take a further look :)

**Comment by Repox** [comment]
Confirmed solved.
