### ISSUE TITLE
Fix your install instructions

### ISSUE THREAD

**Issue by vivekkhurana** [getcandy/hub#40]
Followed the install instructions to the t. But the app doesnt launch. The console is filled with message 
" WARN  You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js."

This message is repeated uncountable times while running npm run dev . Even after the console says listening to localhost:3000, opening it in browser shows nothing. Infact browser is not able to connect to the app. 

There is no firewall or anything as other nuxt.js apps work perfectly fine. Also, nothing in the api logs, infact there is no request that is received in API log.

Really the most pathetic Laravel project I have ever tried.

**Comment by alecritson** [comment]
Hi @vivekkhurana thanks for the feedback. I have managed to follow the instructions myself as they are and got the hub set up and it's all connecting. It might have been worth putting your environment set up in the issue such as node version etc so we can diagnose what's going on.

Although judging by the last sentence I would assume you've decided not to use GetCandy so i'll go ahead and close the issue :)

**Comment by mwamodo** [comment]
Hey @alecritson,

Do you need a postcss.config.js file? I am getting the same error trying to be described. I really like the api and would like to give the hub a try

node version v14.16.0

**Comment by mwamodo** [comment]
works fine with yarn, npm can be really weird sometimes
