### ISSUE TITLE
_vm.fields.options[handle] is undefined

### ISSUE THREAD

**Issue by Ifnir** [getcandy/hub#47]
Page
products.edit.availability

Steps to reproduce:
Click on "Products" in the hub, choose product to edit.

Go into "Availability & Pricing" and click "Add option"

Fill out the form.

`{"variants":[{"sku":"rs5443402","options":{"color":{"en":"Purple"}},"price":"23.00","stock":"","inventory":"2"}]}`

then error response 

`_vm.fields.options[handle] is undefined `

**Comment by alecritson** [comment]
Are you on version `0.12.2` of the hub packages?

If not can you try updating at least `@getcandy/hub-products` to `0.12.2` and see if the issue persists

**Comment by alecritson** [comment]
Should be sorted in `0.12.11` if not then please re open.
