### ISSUE TITLE
Managing availability and pricing on products result in a client error

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#5]
Accessing `catalogue-manager/products/{hashid}/availability-pricing` in the hub results in the client presenting a red dialog box with the header "Internal Server Error" and message "Cannot read property 'id' of undefined"

**Comment by alecritson** [comment]
I wasn't able to reproduce this one, can you let me know if it's still an issue after upgrading.

**Comment by Repox** [comment]
This is still an issue after upgrading.

This is the error I get:

```
TypeError: Cannot read property 'id' of null         client.js?06a0:84
    at Proxy.render (VariantManager.vue?0bf7:313)
    at VueComponent.Vue._render (vue.common.dev.js?4650:3547)
    at VueComponent.updateComponent (vue.common.dev.js?4650:4052)
    at Watcher.get (vue.common.dev.js?4650:4474)
    at Watcher.run (vue.common.dev.js?4650:4549)
    at flushSchedulerQueue (vue.common.dev.js?4650:4307)
    at Array.eval (vue.common.dev.js?4650:1985)
    at flushCallbacks (vue.common.dev.js?4650:1911)
```

**Comment by alecritson** [comment]
This is on a draft/recently published/live product?

**Comment by Repox** [comment]
It's the same result whether it's an already published product or a a draft.

Here's a [gif](https://i.imgur.com/mBm6A41.mp4) showing my exact process.

**Comment by alecritson** [comment]
Looks like the variant hasn't got a tax id associated to it, I assume this is from the seeder. The hub should better handle this thought but for the moment does something like

```
update product_variants set tax_id = 1
```

Solve the issue?

**Comment by alecritson** [comment]
Pushed an update on the products module, should tackle this

```
npm update @getcandy/hub-products
```

**Comment by Repox** [comment]
Adding a tax_id to the `product_variants` solved the issue.

Updated the products module and things worked like expected.
