### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by abdullaadnan** [getcandy/hub#50]
Sir, I am using the tag of 0.12.1 hub after the dev command when I try to login my console gives back 500 as error code also sometimes shows invalid credentials but I am sure that I entered valid credential that I put in the installation process. 
I also check #39 its wasn't work for me

![Screenshot from 2021-04-07 14-48-19](https://user-images.githubusercontent.com/47655583/113843763-80275900-97b1-11eb-8ab5-219f85eaff1c.png)

console screenshot:
![Screenshot from 2021-04-07 14-52-45](https://user-images.githubusercontent.com/47655583/113843801-887f9400-97b1-11eb-8992-b677b33a3ddf.png)

**Comment by alecritson** [comment]
Looks like there are some things missing from your install. Have you gone through all the steps outlined here: https://docs.getcandy.io/api/getting-started/installation.html#installations-steps
