### ISSUE TITLE
Trying to access a category results in a client error

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#6]
When trying to access `catalogue-manager/categories/{hashid}` the client shows a red dialog box with the headline "Internal Server Error" and message "Cannot read property 'replace' of undefined"

**Comment by alecritson** [comment]
This should be addressed in the latest version of the hub and modules, please see upgrade guides

https://guides.getcandy.io/hub-guides/0.9/introduction/upgrading#upgrading-from-091-to-092

If it's still an issue I will take a further look :)

**Comment by Repox** [comment]
Confirmed solved.
