### ISSUE TITLE
Updating customer doesn't send VAT no.

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#7]
When editing a customer, the provided VAT number is not being sent to the API but sent with the value of `null` even though the field has been filled.

**Comment by alecritson** [comment]
This should be addressed in the latest version of the hub and modules, please see upgrade guides

https://guides.getcandy.io/hub-guides/0.9/introduction/upgrading#upgrading-from-091-to-092

If it's still an issue I will take a further look :)

**Comment by Repox** [comment]
Confirmed solved.
